.SILENT:

all: archive

archive:
	mkdir WebSemantique_BRIZAI-THORAVAL
	cp rapport/Alire.pdf WebSemantique_BRIZAI-THORAVAL
	cp -r requetes WebSemantique_BRIZAI-THORAVAL
	cp siege.owl WebSemantique_BRIZAI-THORAVAL 
	tar cfvz WebSemantique_BRIZAI-THORAVAL.tgz WebSemantique_BRIZAI-THORAVAL
	rm -rf WebSemantique_BRIZAI-THORAVAL/
